// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atprkawiwlwuozyijlsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0cHJrYXdpd2x3dW96eWlqbHNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNzA2NzQsImV4cCI6MjA2Nzc0NjY3NH0.DAqca7rpDX-Vr2TK3vdKUzUGLasI9cJ1fZzGtkPQ6qc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});